# Google Calendar Events

* Nate Cooper's Birthday
<2025-08-23 Sat>

* Dinner Abby Nick
<2025-08-23 Sat 17:30-19:00>

* Trash Out
<2025-08-24 Sun>

* Vanessa Homewood's Birthday
<2025-08-26 Tue>
This is an event reminder

* Meetali Kerawalla's Birthday
<2025-08-31 Sun>

* Trash Out
<2025-08-31 Sun>

* Hallie Parry's Birthday
<2025-09-02 Tue>

* James massage
<2025-09-03 Wed 11:30-12:00>

* Flight to San Francisco (UA 1665)
<2025-09-04 Thu 17:27-22:08>
United Airlines flight 1665\nNew Orleans MSY 5:27pm (local time
Location: New Orleans MSY

* Trash Out
<2025-09-07 Sun>

* Flight to New Orleans (UA 246)
<2025-09-10 Wed 12:01-16:17>
United Airlines flight 246\nSan Francisco SFO 10:01am (local ti
Location: San Francisco SFO

* Trash Out
<2025-09-14 Sun>

* Marley
<2025-09-17 Wed 15:00-15:30>

* Dr. Braddy in Spine Center\, Ochsner Baptist
<2025-09-19 Fri 13:00-13:45>
Location:  Ochsner Baptist 

* Trash Out
<2025-09-21 Sun>

* Laura Arrives at MSY
<2025-09-21 Sun 17:50-19:00>
SWA Flight 1849 Sunday 09/21/25 \nPassenger: Laura Smetanick\nD
Location: 1 Terminal Dr\, Kenner\, LA 70062

* Michelle  Sartor's birthday
<2025-09-22 Mon>

* Liz Balsam's Birthday
<2025-09-24 Wed>
This is an event reminder

* Brittni
<2025-09-24 Wed 13:30-14:00>

* Review Carrollton Construction Analysis
<2025-09-24 Wed 15:00-16:30>
Join with Google Meet: https://meet.google.com/zev-qjor-uhz\n\n

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2025-09-25 Thu>
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* CVS and liquor store
<2025-09-25 Thu 10:00-10:30>

* Trash Out
<2025-09-28 Sun>

* Danneel Meeting @ Martin's 
<2025-09-30 Tue 14:00-16:00>
Craig Jennings\nHey everyone -- I hope y'all are doing well. I 
Location: Martin’s: Wine\, Liquor\, Beer & Deli - New Orleans\, 3827 Baronne

* Brady Lester's Birthday
<2025-10-02 Thu>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2025-10-02 Thu>
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Dinner at The Husky with Abby\, Nick
<2025-10-03 Fri 20:00-22:00>
Join with Google Meet: https://meet.google.com/zrx-srqr-mkt\n\n

* Prisca Weem's Birthday
<2025-10-04 Sat>

* Trash Out
<2025-10-05 Sun>

* Martin\, GC\, Kelly
<2025-10-07 Tue 14:00-15:00>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2025-10-09 Thu>
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Harmick/Vahagn <> Craig catch up
<2025-10-09 Thu 10:00-10:40>
Hi Craig<br><br>Thanks again for agreeing to meet with us<br><b

* Call Mom
<2025-10-09 Thu 12:00-13:00>
Testing where the notes go....

* Amy pain management for Christine
<2025-10-10 Fri 11:40-12:10>

* Trash Out
<2025-10-12 Sun>

* Craig/Arusyak Chat
<2025-10-13 Mon 11:30-12:30>
\n~-~-~-~-~-~-~%~!~%~!~%~!~%~!~%~!~%~!~%~!~%~!~%~!~%~!~%~!~%~!~

* Foursevens Quark Onibi Debut
<2025-10-14 Tue>
This is an event reminder

* Susan Moynihan's Birthday
<2025-10-14 Tue>

* Dr. Braddy -- Pain Mgmt
<2025-10-14 Tue 13:30-14:15>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2025-10-16 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Post Office: Check to Teresa
<2025-10-16 Thu 11:00-11:30>

* CVS: Pick up Your and Xtine Prescriptions
<2025-10-16 Thu 11:30-12:00>

* French Truck: Coffee / Lunch
<2025-10-16 Thu 12:00-12:30>

* Walk Back
<2025-10-16 Thu 12:30-13:00>

* Call with AJ Fudge
<2025-10-16 Thu 13:00-14:00>

* GTFO
<2025-10-18 Sat 10:30-11:00>

* Pete's Pirate Life Drop
<2025-10-18 Sat 11:00-11:30>

* High school reunion 40th
<2025-10-18 Sat 19:00-19:30>

* Baby Fart Day
<2025-10-19 Sun>
Making it an official all-day event. Attendance mandatory. Loca

* Trash Out
<2025-10-19 Sun>

* Daniel Pham's birthday
<2025-10-22 Wed>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2025-10-23 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* John Smetanick's Birthday
<2025-10-24 Fri>
This is an event reminder

* Reminder: Arrange for Tile Delivery
<2025-10-24 Fri 09:00-09:30>
On Wed Sept 24th we received a call from the tile place who sai

* Danneel Street Project Meeting
<2025-10-24 Fri 10:00-11:00>
Craig\,<br><br>Jeff and I are both available tomorrow morning f
Location: 3824 Nashville Ave\, New Orleans\, LA 70125\, USA

* GTFO
<2025-10-25 Sat 10:30-11:00>

* Louisa Housekeeping
<2025-10-25 Sat 11:00-16:00>

* Trash Out
<2025-10-26 Sun>

* Phone Meeting with Arusyak
<2025-10-26 Sun 10:00-11:00>
<a href="https://us05web.zoom.us/j/85337619651?pwd=KpBnpye1tahE

* Brunch @ Katie's
<2025-10-26 Sun 11:30-14:00>
Join with Google Meet: https://meet.google.com/dny-xfoy-umz\n\n
Location: Katie's\, 3701 Iberville St\, New Orleans\, LA 70119\, USA

* Order and Pick up Lunch for Danneel Project Meeting
<2025-10-27 Mon 11:00-12:00>

* Meet with Mark and Jeff
<2025-10-27 Mon 12:00-12:45>
Join with Google Meet: https://meet.google.com/cpp-tuxm-kyx\n\n
Location: 3824 Nashville Ave\, New Orleans\, LA 70125\, USA

* Haircut with Ashley @ Aidan Gill
<2025-10-28 Tue 14:00-14:30>
This is an event reminder
Location: Aidan Gill For Men\, 2026 Magazine St\, New Orleans\, LA 70130\, U

* Reply to AJ
<2025-10-29 Wed 11:00-14:00>

* Change.Yale Lock Batteries
<2025-10-30 Thu>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2025-10-30 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Answer All Email and Linked In Messages
<2025-10-30 Thu 13:00-14:00>

* Work On Disclosures
<2025-10-30 Thu 14:00-18:30>

* Fill Out Pre-Check In
<2025-10-30 Thu 18:30-19:00>

* Fasting Begins
<2025-10-30 Thu 19:00-07:00>
\n1. Do not eat or drink anything for TEN HOURS (10) PRIOR TO T

* Leave for Dr Fernandez Appt
<2025-10-31 Fri 06:30-07:00>

* Appt Dr Fernandez
<2025-10-31 Fri 07:00-08:00>
\nJeff Hwy Lab - Primary Care Bldg\n\n1401 Jefferson Hwy\nNew O
Location: 1401 Jefferson Ave\, New Orleans\, LA 70115\, USA

* Call with Jonathan Schlutis lawyer
<2025-10-31 Fri 10:00-10:30>

* Call with Jon at Reiss
<2025-10-31 Fri 11:00-11:30>

* Renew DMV Registration By Mail
<2025-10-31 Fri 13:00-14:00>

* File IRS Form 56
<2025-10-31 Fri 14:00-15:00>

* Get EIN Tax ID Number
<2025-10-31 Fri 15:00-16:00>

* GTFO
<2025-11-01 Sat 10:30-11:00>

* Louisa Housekeeping
<2025-11-01 Sat 11:00-16:00>

* Trash Out
<2025-11-02 Sun>

* Transit to Meeting
<2025-11-03 Mon 10:00-10:30>

* Mark Wetmore
<2025-11-03 Mon 10:30-11:00>
This is an event reminder
Location: French Truck Coffee\, 4536 Dryades St\, New Orleans\, LA 70115\, U

* Meeting with AJ
<2025-11-04 Tue 12:00-13:00>

* Olle Kjellgren\, MD - Cardiologist
<2025-11-04 Tue 15:30-16:00>
Phone: 504-894-2560\n\n\nPlease arrive approximately 15 minutes
Location: 2820 Napoleon Avenue\, Suite 230\, New Orleans LA 70115-6969

* Physical Therapy with Jasmyn Chaisson
<2025-11-05 Wed 13:30-14:30>
Phone: 504-894-2002\n
Location: 2820 Napoleon Avenue\, Suite 450\, New Orleans LA 70115-8229

* Phone Call with Craig and Justin
<2025-11-05 Wed 16:30-17:30>
<br><br><br><br>Christine Ciarmello<br><br><br><div dir="auto">

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2025-11-06 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Call Mark Wetmore
<2025-11-07 Fri 10:30-11:30>
(504) 799-5697

* GTFO
<2025-11-08 Sat 10:30-11:00>

* Louisa Housekeeping
<2025-11-08 Sat 11:00-16:00>

* Trash Out
<2025-11-09 Sun>

* Call the Probate Court
<2025-11-10 Mon 14:00-14:30>

* DEADLINE Send Response to Mark Wetmore
<2025-11-10 Mon 16:00-16:30>

* Shower
<2025-11-11 Tue 11:00-11:30>

* org-msg improvements
<2025-11-11 Tue 13:00-16:00>

* Craig / Ryan
<2025-11-12 Wed 10:00-11:00>
Join with Google Meet: https://meet.google.com/kgb-ngmj-tez\nOr

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2025-11-13 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Call with Jonathan Schultis
<2025-11-13 Thu 14:00-14:30>
<p>P: 504.304.7115  Ext. 1002</p><p>D: 504.309.1051</p>\n\nJoin

* GTFO
<2025-11-15 Sat 10:30-11:00>

* Pick up Prescriptions at CVS
<2025-11-15 Sat 11:00-12:00>

* Louisa Housekeeping
<2025-11-15 Sat 11:00-16:00>

* Trash Out
<2025-11-16 Sun>

* Pick Up Prescriptions at CVS
<2025-11-16 Sun 14:30-15:00>

* Drive Christine to Clearview
<2025-11-17 Mon 07:30-08:00>

* Injection at Clearview
<2025-11-17 Mon 08:00-08:30>

* Talk with Shane about Tenants
<2025-11-17 Mon 16:15-16:45>

* Finish and Send Email to Jon Schultis
<2025-11-17 Mon 17:00-18:00>

* Passport Renewal Work
<2025-11-17 Mon 18:30-19:30>

* Driver's License Renewal Work
<2025-11-17 Mon 19:30-20:30>

* Send Laura Tasks for HB
<2025-11-17 Mon 20:30-21:00>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2025-11-20 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2025-11-22 Sat 10:30-11:00>

* Louisa Housekeeping
<2025-11-22 Sat 11:00-16:00>

* Trash Out
<2025-11-23 Sun>

* Pick up Thanksgiving Order at Lagniappe
<2025-11-26 Wed>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2025-11-27 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2025-11-29 Sat 10:30-11:00>

* Louisa Housekeeping
<2025-11-29 Sat 11:00-16:00>

* Trash Out
<2025-11-30 Sun>

* Southwest Flight PVD
<2025-12-03 Wed 10:40-16:30>
<br><br><b>confirmation\, </b><b>AV6IHB</b><br><b><br></b><br><

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2025-12-04 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2025-12-06 Sat 10:30-11:00>

* Louisa Housekeeping
<2025-12-06 Sat 11:00-16:00>

* Trash Out
<2025-12-07 Sun>

* Blake Michael's Birthday
<2025-12-09 Tue>
Blake was born in 1999

* Pay healthcare premium for 2026
<2025-12-10 Wed 14:00-14:30>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2025-12-11 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Craig / Ryan
<2025-12-12 Fri 10:00-11:00>
Join with Google Meet: https://meet.google.com/kgb-ngmj-tez\nOr

* Augusta Baty Birthday
<2025-12-13 Sat>
This is an event reminder

* GTFO
<2025-12-13 Sat 10:30-11:00>

* Louisa Housekeeping
<2025-12-13 Sat 11:00-16:00>

* Trash Out
<2025-12-14 Sun>

* Saradha's Birthday
<2025-12-17 Wed>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2025-12-18 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Blake Michael's birthday
<2025-12-19 Fri>

* GTFO
<2025-12-20 Sat 10:30-11:00>

* Louisa Housekeeping
<2025-12-20 Sat 11:00-16:00>

* Trash Out
<2025-12-21 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2025-12-25 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2025-12-27 Sat 10:30-11:00>

* Louisa Housekeeping
<2025-12-27 Sat 11:00-16:00>

* Trash Out
<2025-12-28 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-01-01 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-01-03 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-01-03 Sat 11:00-16:00>

* Trash Out
<2026-01-04 Sun>

* Amy Oregon
<2026-01-06 Tue 10:20-10:50>

* New Patient with Lynsi Blanchard\, PA-C
<2026-01-07 Wed 13:30-14:00>
Arrival Location: BAPC SLEEP CLINIC\nPhone: 504-842-4910\n\n\nP
Location: 2820 Napoleon Ave\, Ste 590\, New Orleans LA 70115-8209

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-01-08 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-01-10 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-01-10 Sat 11:00-16:00>

* Trash Out
<2026-01-11 Sun>

* Craig / Ryan
<2026-01-12 Mon 10:00-11:00>
Join with Google Meet: https://meet.google.com/kgb-ngmj-tez\nOr

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-01-15 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-01-17 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-01-17 Sat 11:00-16:00>

* Trash Out
<2026-01-18 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-01-22 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-01-24 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-01-24 Sat 11:00-16:00>

* Trash Out
<2026-01-25 Sun>

* Christy Gordon Baty Birthday
<2026-01-28 Wed>
This is an event reminder

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-01-29 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Cesar Birthday
<2026-01-29 Thu 10:00-10:30>
Join with Google Meet: https://meet.google.com/hgw-ceaa-mfa\n\n

* Change.Yale Lock Batteries
<2026-01-30 Fri>

* GTFO
<2026-01-31 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-01-31 Sat 11:00-16:00>

* Mom and Johns Anniversary
<2026-02-01 Sun>

* Trash Out
<2026-02-01 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-02-05 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Nine Inch Nails
<2026-02-05 Thu 19:00-21:00>
Nine Inch Nails bring the Peel It Back Tour 2026 to New Orleans
Location: Smoothie King Center\, 1501 Dave Dixon Dr Space 101-102\, New Orle

* GTFO
<2026-02-07 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-02-07 Sat 11:00-16:00>

* Trash Out
<2026-02-08 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-02-12 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Craig / Ryan
<2026-02-12 Thu 10:00-11:00>
Join with Google Meet: https://meet.google.com/kgb-ngmj-tez\nOr

* GTFO
<2026-02-14 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-02-14 Sat 11:00-16:00>

* Trash Out
<2026-02-15 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-02-19 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Sara Essex Bradley Birthday
<2026-02-21 Sat>

* GTFO
<2026-02-21 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-02-21 Sat 11:00-16:00>

* Trash Out
<2026-02-22 Sun>

* Bri
<2026-02-23 Mon 12:15-12:45>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-02-26 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-02-28 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-02-28 Sat 11:00-16:00>

* Anniversary
<2026-03-01 Sun>
This is an event reminder

* Trash Out
<2026-03-01 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-03-05 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-03-07 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-03-07 Sat 11:00-16:00>

* Trash Out
<2026-03-08 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-03-12 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Craig / Ryan
<2026-03-12 Thu 10:00-11:00>
Join with Google Meet: https://meet.google.com/kgb-ngmj-tez\nOr

* Pi Day!
<2026-03-14 Sat>

* GTFO
<2026-03-14 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-03-14 Sat 11:00-16:00>

* Louisa Birthday
<2026-03-15 Sun>
Join with Google Meet: https://meet.google.com/myx-kkcm-nav\n\n

* Trash Out
<2026-03-15 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-03-19 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-03-21 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-03-21 Sat 11:00-16:00>

* Trash Out
<2026-03-22 Sun>

* Rajani Ramanathan's Birthday
<2026-03-25 Wed>
------------\nFrom:Lauren Peterson\nSent:Monday\, March 25\, 20

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-03-26 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Gracie's Birthday
<2026-03-27 Fri>
This is an event reminder

* GTFO
<2026-03-28 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-03-28 Sat 11:00-16:00>

* Trash Out
<2026-03-29 Sun>

* Gabi Birthday
<2026-03-31 Tue>
This is an event reminder

* POD Return Date
<2026-04-01 Wed>

* Sanjeevani Bhardwaj's Birthday
<2026-04-02 Thu>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-04-02 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-04-04 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-04-04 Sat 11:00-16:00>

* Trash Out
<2026-04-05 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-04-09 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Anniversary: SF
<2026-04-11 Sat>
Christine and I got married in City Hall this day

* GTFO
<2026-04-11 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-04-11 Sat 11:00-16:00>

* Trash Out
<2026-04-12 Sun>

* Craig / Ryan
<2026-04-12 Sun 10:00-11:00>
Join with Google Meet: https://meet.google.com/kgb-ngmj-tez\nOr

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-04-16 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-04-18 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-04-18 Sat 11:00-16:00>

* Trash Out
<2026-04-19 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-04-23 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-04-25 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-04-25 Sat 11:00-16:00>

* Trash Out
<2026-04-26 Sun>

* Change.Yale Lock Batteries
<2026-04-30 Thu>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-04-30 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-05-02 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-05-02 Sat 11:00-16:00>

* Trash Out
<2026-05-03 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-05-07 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-05-09 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-05-09 Sat 11:00-16:00>

* Trash Out
<2026-05-10 Sun>

* Craig / Ryan
<2026-05-12 Tue 10:00-11:00>
Join with Google Meet: https://meet.google.com/kgb-ngmj-tez\nOr

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-05-14 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-05-16 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-05-16 Sat 11:00-16:00>

* Trash Out
<2026-05-17 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-05-21 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-05-23 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-05-23 Sat 11:00-16:00>

* Trash Out
<2026-05-24 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-05-28 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-05-30 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-05-30 Sat 11:00-16:00>

* Trash Out
<2026-05-31 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-06-04 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-06-06 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-06-06 Sat 11:00-16:00>

* Trash Out
<2026-06-07 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-06-11 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Craig / Ryan
<2026-06-12 Fri 10:00-11:00>
Join with Google Meet: https://meet.google.com/kgb-ngmj-tez\nOr

* GTFO
<2026-06-13 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-06-13 Sat 11:00-16:00>

* Trash Out
<2026-06-14 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-06-18 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-06-20 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-06-20 Sat 11:00-16:00>

* Trash Out
<2026-06-21 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-06-25 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Christine's Birthday
<2026-06-27 Sat>
Born this day in 1968

* GTFO
<2026-06-27 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-06-27 Sat 11:00-16:00>

* Trash Out
<2026-06-28 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-07-02 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-07-04 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-07-04 Sat 11:00-16:00>

* Trash Out
<2026-07-05 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-07-09 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-07-11 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-07-11 Sat 11:00-16:00>

* Lucy Nischwitz's birthday
<2026-07-12 Sun>

* Trash Out
<2026-07-12 Sun>

* Craig / Ryan
<2026-07-12 Sun 10:00-11:00>
Join with Google Meet: https://meet.google.com/kgb-ngmj-tez\nOr

* Kevin Michael's Birthday
<2026-07-14 Tue>
This is an event reminder

* Chase Michael's Birthday
<2026-07-15 Wed>
This is an event reminder

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-07-16 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-07-18 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-07-18 Sat 11:00-16:00>

* Trash Out
<2026-07-19 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-07-23 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-07-25 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-07-25 Sat 11:00-16:00>

* Trash Out
<2026-07-26 Sun>

* Change.Yale Lock Batteries
<2026-07-30 Thu>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-07-30 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-08-01 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-08-01 Sat 11:00-16:00>

* Trash Out
<2026-08-02 Sun>

* Vivi Baty Birthday
<2026-08-04 Tue>
This is an event reminder

* Laura Smetanick's birthday
<2026-08-05 Wed>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-08-06 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-08-08 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-08-08 Sat 11:00-16:00>

* Trash Out
<2026-08-09 Sun>

* Doody's Birthday
<2026-08-09 Sun 08:15-08:45>

* Craig / Ryan
<2026-08-12 Wed 10:00-11:00>
Join with Google Meet: https://meet.google.com/kgb-ngmj-tez\nOr

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-08-13 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-08-15 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-08-15 Sat 11:00-16:00>

* Trash Out
<2026-08-16 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-08-20 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-08-22 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-08-22 Sat 11:00-16:00>

* Nate Cooper's Birthday
<2026-08-23 Sun>

* Trash Out
<2026-08-23 Sun>

* Vanessa Homewood's Birthday
<2026-08-26 Wed>
This is an event reminder

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-08-27 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-08-29 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-08-29 Sat 11:00-16:00>

* Trash Out
<2026-08-30 Sun>

* Meetali Kerawalla's Birthday
<2026-08-31 Mon>

* Hallie Parry's Birthday
<2026-09-02 Wed>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-09-03 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-09-05 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-09-05 Sat 11:00-16:00>

* Trash Out
<2026-09-06 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-09-10 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Craig / Ryan
<2026-09-12 Sat 10:00-11:00>
Join with Google Meet: https://meet.google.com/kgb-ngmj-tez\nOr

* GTFO
<2026-09-12 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-09-12 Sat 11:00-16:00>

* Trash Out
<2026-09-13 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-09-17 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-09-19 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-09-19 Sat 11:00-16:00>

* Trash Out
<2026-09-20 Sun>

* Michelle  Sartor's birthday
<2026-09-22 Tue>

* Liz Balsam's Birthday
<2026-09-24 Thu>
This is an event reminder

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-09-24 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-09-26 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-09-26 Sat 11:00-16:00>

* Trash Out
<2026-09-27 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-10-01 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Brady Lester's Birthday
<2026-10-02 Fri>

* GTFO
<2026-10-03 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-10-03 Sat 11:00-16:00>

* Prisca Weem's Birthday
<2026-10-04 Sun>

* Trash Out
<2026-10-04 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-10-08 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-10-10 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-10-10 Sat 11:00-16:00>

* Trash Out
<2026-10-11 Sun>

* Craig / Ryan
<2026-10-12 Mon 10:00-11:00>
Join with Google Meet: https://meet.google.com/kgb-ngmj-tez\nOr

* Susan Moynihan's Birthday
<2026-10-14 Wed>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-10-15 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-10-17 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-10-17 Sat 11:00-16:00>

* Trash Out
<2026-10-18 Sun>

* Baby Fart Day
<2026-10-19 Mon>
Making it an official all-day event. Attendance mandatory. Loca

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-10-22 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Daniel Pham's birthday
<2026-10-22 Thu>

* John Smetanick's Birthday
<2026-10-24 Sat>
This is an event reminder

* GTFO
<2026-10-24 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-10-24 Sat 11:00-16:00>

* Trash Out
<2026-10-25 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-10-29 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Change.Yale Lock Batteries
<2026-10-30 Fri>

* GTFO
<2026-10-31 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-10-31 Sat 11:00-16:00>

* Trash Out
<2026-11-01 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-11-05 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* GTFO
<2026-11-07 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-11-07 Sat 11:00-16:00>

* Trash Out
<2026-11-08 Sun>

* Lagniappe Bakehouse Is Open 8 AM–1 PM
<2026-11-12 Thu>
This is an event reminder
Location: 1825 Euterpe St\, New Orleans\, LA 70113

* Craig / Ryan
<2026-11-12 Thu 10:00-11:00>
Join with Google Meet: https://meet.google.com/kgb-ngmj-tez\nOr

* GTFO
<2026-11-14 Sat 10:30-11:00>

* Louisa Housekeeping
<2026-11-14 Sat 11:00-16:00>

* Trash Out
<2026-11-15 Sun>
